spring:
  application:
    name: client-service
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_test
    username: root
    password: mysql

server:
  port: 9003

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
        defaultZone: http://localhost:9001/eureka
